# kind cluster configuration file

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  # Control plane node
  - role: control-plane
    image: kindest/node:v1.31.2

  # Worker nodes
  - role: worker
    image: kindest/node:v1.31.2

  - role: worker
    image: kindest/node:v1.31.2

  - role: worker
    image: kindest/node:v1.31.2
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP

